apiVersion: v1
kind: Service
metadata:
  name: asocijacije-service
  namespace: asocijacije
  labels:
    app: asocijacije
spec:
  selector:
    app: asocijacije
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
